// <auto-generated />
using System;
using System.Collections.Generic;
using DiceEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiceEngine.Infrastructure.Migrations
{
    [DbContext(typeof(DiceEngineDbContext))]
    [Migration("20260128095305_AddCharacterManagement")]
    partial class AddCharacterManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiceEngine.Domain.Entities.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentSceneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Dictionary<string, object>>("GameState")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("CurrentSceneId");

                    b.HasIndex("GameState");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GameState"), "gin");

                    b.HasIndex("LastUpdatedAt")
                        .IsDescending();

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChaBase")
                        .HasColumnType("integer");

                    b.Property<int>("ConBase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DexBase")
                        .HasColumnType("integer");

                    b.Property<int>("IntBase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StrBase")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CharacterSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChaBase")
                        .HasColumnType("integer");

                    b.Property<int>("ChaModifier")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConBase")
                        .HasColumnType("integer");

                    b.Property<int>("ConModifier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DexBase")
                        .HasColumnType("integer");

                    b.Property<int>("DexModifier")
                        .HasColumnType("integer");

                    b.Property<int>("IntBase")
                        .HasColumnType("integer");

                    b.Property<int>("IntModifier")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StrBase")
                        .HasColumnType("integer");

                    b.Property<int>("StrModifier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CharacterId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("character_snapshots", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Character", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Adventure", null)
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CharacterSnapshot", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Character", "Character")
                        .WithMany("Snapshots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Character", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
