// <auto-generated />
using System;
using System.Collections.Generic;
using DiceEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiceEngine.Infrastructure.Migrations
{
    [DbContext(typeof(DiceEngineDbContext))]
    [Migration("20260203145616_PendingChanges")]
    partial class PendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiceEngine.Domain.Entities.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentSceneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Dictionary<string, object>>("GameState")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("CurrentSceneId");

                    b.HasIndex("GameState");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GameState"), "gin");

                    b.HasIndex("LastUpdatedAt")
                        .IsDescending();

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChaBase")
                        .HasColumnType("integer");

                    b.Property<int>("ConBase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DexBase")
                        .HasColumnType("integer");

                    b.Property<int>("IntBase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StrBase")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CharacterSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChaBase")
                        .HasColumnType("integer");

                    b.Property<int>("ChaModifier")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConBase")
                        .HasColumnType("integer");

                    b.Property<int>("ConModifier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DexBase")
                        .HasColumnType("integer");

                    b.Property<int>("DexModifier")
                        .HasColumnType("integer");

                    b.Property<int>("IntBase")
                        .HasColumnType("integer");

                    b.Property<int>("IntModifier")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StrBase")
                        .HasColumnType("integer");

                    b.Property<int>("StrModifier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CharacterId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("character_snapshots", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CombatEncounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTurnIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiativeOrder")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Winner")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("Status");

                    b.ToTable("combat_encounters", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Combatant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CombatEncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CombatantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<int>("DexterityModifier")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EnemyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EquippedWeaponId")
                        .HasColumnType("uuid");

                    b.Property<int>("InitiativeRoll")
                        .HasColumnType("integer");

                    b.Property<int>("InitiativeScore")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TiebreakerKey")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CombatEncounterId");

                    b.HasIndex("CombatEncounterId", "InitiativeScore")
                        .IsDescending(false, true);

                    b.HasIndex("CombatEncounterId", "Status");

                    b.ToTable("combatants", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Enemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("ChaBase")
                        .HasColumnType("integer");

                    b.Property<int>("ConBase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentAIState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DexBase")
                        .HasColumnType("integer");

                    b.Property<string>("EquippedWeaponInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("FleeHealthThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("IntBase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StrBase")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Name");

                    b.ToTable("enemies", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.EquipmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EquippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EquippedItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CharacterId1");

                    b.HasIndex("EquippedItemId");

                    b.HasIndex("CharacterId", "SlotType")
                        .IsUnique();

                    b.ToTable("equipment_slots", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.FailureCondition", b =>
                {
                    b.Property<Guid>("FailureConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionType")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.HasKey("FailureConditionId");

                    b.HasIndex("StageId");

                    b.ToTable("failure_conditions", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.InventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotPosition")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("ItemId");

                    b.HasIndex("AdventureId", "ItemId");

                    b.ToTable("inventory_entries", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("loot_tables", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LootTableId");

                    b.ToTable("loot_table_entries", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.ObjectiveProgress", b =>
                {
                    b.Property<Guid>("ObjectiveProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageProgressId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetAmount")
                        .HasColumnType("integer");

                    b.HasKey("ObjectiveProgressId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("StageProgressId");

                    b.ToTable("objective_progress", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcurrentPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("QuestId");

                    b.HasIndex("Difficulty");

                    b.HasIndex("Name");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestDependency", b =>
                {
                    b.Property<Guid>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependentQuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrerequisiteQuestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("DependencyId");

                    b.HasIndex("PrerequisiteQuestId");

                    b.HasIndex("DependentQuestId", "PrerequisiteQuestId")
                        .IsUnique();

                    b.ToTable("quest_dependencies", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestObjective", b =>
                {
                    b.Property<Guid>("ObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConditionType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<int>("ObjectiveNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetAmount")
                        .HasColumnType("integer");

                    b.HasKey("ObjectiveId");

                    b.HasIndex("StageId", "ObjectiveNumber")
                        .IsUnique();

                    b.ToTable("quest_objectives", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestProgress", b =>
                {
                    b.Property<Guid>("QuestProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AbandonedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStageNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("QuestProgressId");

                    b.HasIndex("QuestId");

                    b.HasIndex("PlayerId", "QuestId")
                        .IsUnique();

                    b.HasIndex("PlayerId", "Status");

                    b.ToTable("quest_progress", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestReward", b =>
                {
                    b.Property<Guid>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("ItemId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("RewardId");

                    b.HasIndex("QuestId");

                    b.HasIndex("StageId");

                    b.ToTable("quest_rewards", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestStage", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<int>("StageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("StageId");

                    b.HasIndex("QuestId", "StageNumber")
                        .IsUnique();

                    b.ToTable("quest_stages", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.StageProgress", b =>
                {
                    b.Property<Guid>("StageProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestProgressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<int>("StageNumber")
                        .HasColumnType("integer");

                    b.HasKey("StageProgressId");

                    b.HasIndex("QuestProgressId");

                    b.HasIndex("StageId");

                    b.ToTable("stage_progress", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.ValueObjects.AttackAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackRoll")
                        .HasColumnType("integer");

                    b.Property<int>("AttackTotal")
                        .HasColumnType("integer");

                    b.Property<Guid>("AttackerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CombatEncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DamageExpression")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("DamageRoll")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCriticalHit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHit")
                        .HasColumnType("boolean");

                    b.Property<int>("TargetAC")
                        .HasColumnType("integer");

                    b.Property<int>("TargetHealthAfter")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalDamage")
                        .HasColumnType("integer");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CombatEncounterId");

                    b.HasIndex("CombatEncounterId", "Timestamp");

                    b.ToTable("attack_actions", (string)null);
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.StackableItem", b =>
                {
                    b.HasBaseType("DiceEngine.Domain.Entities.Item");

                    b.Property<int>("MaxStackSize")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Stackable");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.UniqueItem", b =>
                {
                    b.HasBaseType("DiceEngine.Domain.Entities.Item");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SlotType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasDiscriminator().HasValue("Unique");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Character", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Adventure", null)
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CharacterSnapshot", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Character", "Character")
                        .WithMany("Snapshots")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CombatEncounter", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Adventure", null)
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Combatant", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.CombatEncounter", null)
                        .WithMany("Combatants")
                        .HasForeignKey("CombatEncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.EquipmentSlot", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiceEngine.Domain.Entities.Character", null)
                        .WithMany("EquipmentSlots")
                        .HasForeignKey("CharacterId1");

                    b.HasOne("DiceEngine.Domain.Entities.UniqueItem", "EquippedItem")
                        .WithMany()
                        .HasForeignKey("EquippedItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("EquippedItem");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.FailureCondition", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.QuestStage", "Stage")
                        .WithMany("FailureConditions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.InventoryEntry", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Adventure", "Adventure")
                        .WithMany()
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiceEngine.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adventure");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.LootTableEntry", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiceEngine.Domain.Entities.LootTable", "LootTable")
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.ObjectiveProgress", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.QuestObjective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiceEngine.Domain.Entities.StageProgress", "StageProgress")
                        .WithMany("ObjectiveProgress")
                        .HasForeignKey("StageProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");

                    b.Navigation("StageProgress");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestDependency", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Quest", "DependentQuest")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependentQuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiceEngine.Domain.Entities.Quest", "PrerequisiteQuest")
                        .WithMany("DependentQuests")
                        .HasForeignKey("PrerequisiteQuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentQuest");

                    b.Navigation("PrerequisiteQuest");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestObjective", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.QuestStage", "Stage")
                        .WithMany("Objectives")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestProgress", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestReward", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Quest", "Quest")
                        .WithMany("Rewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DiceEngine.Domain.Entities.QuestStage", "Stage")
                        .WithMany("StageRewards")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Quest");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestStage", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.Quest", "Quest")
                        .WithMany("Stages")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.StageProgress", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.QuestProgress", "QuestProgress")
                        .WithMany("StageProgress")
                        .HasForeignKey("QuestProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiceEngine.Domain.Entities.QuestStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestProgress");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DiceEngine.Domain.ValueObjects.AttackAction", b =>
                {
                    b.HasOne("DiceEngine.Domain.Entities.CombatEncounter", null)
                        .WithMany("CompletedActions")
                        .HasForeignKey("CombatEncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Character", b =>
                {
                    b.Navigation("EquipmentSlots");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.CombatEncounter", b =>
                {
                    b.Navigation("Combatants");

                    b.Navigation("CompletedActions");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.LootTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.Quest", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentQuests");

                    b.Navigation("Rewards");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestProgress", b =>
                {
                    b.Navigation("StageProgress");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.QuestStage", b =>
                {
                    b.Navigation("FailureConditions");

                    b.Navigation("Objectives");

                    b.Navigation("StageRewards");
                });

            modelBuilder.Entity("DiceEngine.Domain.Entities.StageProgress", b =>
                {
                    b.Navigation("ObjectiveProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
