/**
 * Character Management Type Definitions
 * Represents domain models for character creation, editing, and display
 * Based on D&D 5E attribute system (3-18 range for attributes)
 */

/**
 * Attribute keys for type safety when accessing character attributes
 */
export type AttributeKey = "str" | "dex" | "int" | "con" | "cha";

/**
 * Attributes object structure used throughout the application
 */
export interface Attributes {
  str: number; // Strength
  dex: number; // Dexterity
  int: number; // Intelligence
  con: number; // Constitution
  cha: number; // Charisma
}

/**
 * Represents a player character with D&D 5E attributes and calculated modifiers.
 * This is the primary domain model for persisted character data from the backend.
 *
 * @example
 * ```typescript
 * const character: Character = {
 *   id: "550e8400-e29b-41d4-a716-446655440000",
 *   name: "Gandalf the Grey",
 *   adventureId: "adventure-123",
 *   attributes: { str: 10, dex: 12, int: 18, con: 14, cha: 16 },
 *   modifiers: { str: 0, dex: 1, int: 4, con: 2, cha: 3 },
 *   createdAt: "2026-01-30T10:00:00Z",
 *   updatedAt: "2026-01-30T10:00:00Z"
 * };
 * ```
 */
export interface Character {
  // Identity and relationships
  /** Unique identifier (UUID) generated by backend */
  id: string;

  /** Character name (1-50 characters) */
  name: string;

  /** Foreign key to adventure this character belongs to */
  adventureId: string;

  // Base Attributes (3-18 range per D&D 5E standard)
  /**
   * Base attribute values before any modifiers
   * Each value: integer between 3 and 18 inclusive
   */
  attributes: Attributes;

  // Calculated Modifiers (derived: floor((value - 10) / 2))
  /**
   * Calculated modifiers based on attributes
   * Formula: floor((attributeValue - 10) / 2)
   * Range: -4 to +4
   */
  modifiers: Attributes;

  // Metadata
  /** ISO 8601 timestamp of character creation */
  createdAt: string;

  /** ISO 8601 timestamp of last update */
  updatedAt: string;
}

/**
 * Form data for character creation or editing.
 * Represents intermediate state during form entry, not yet persisted.
 * Used as the request payload when creating or updating characters via API.
 *
 * @example
 * ```typescript
 * const formData: CharacterFormData = {
 *   name: "Aragorn",
 *   adventureId: "adventure-456",
 *   attributes: { str: 15, dex: 14, int: 12, con: 16, cha: 17 }
 * };
 * ```
 */
export interface CharacterFormData {
  // Basic Info
  /** Character name as entered in form (can be empty until submission) */
  name: string;

  /** Adventure ID this character is being created for */
  adventureId: string;

  // Attribute Allocation
  /**
   * Attribute values as entered/selected by user
   * During form entry, these are the user's choices
   * Range: 3-18 (validated before submission)
   */
  attributes: Attributes;
}

/**
 * Character summary for list and preview displays.
 * Contains all data from Character but used in contexts where
 * full detail is not needed (e.g., character lists, adventure selection)
 *
 * @example
 * ```typescript
 * const listItem: CharacterListItem = {
 *   id: "char-789",
 *   name: "Legolas",
 *   attributes: { str: 11, dex: 18, int: 14, con: 13, cha: 12 },
 *   createdAt: "2026-01-29T15:30:00Z"
 * };
 * ```
 */
export interface CharacterListItem extends Omit<
  Character,
  "modifiers" | "updatedAt"
> {
  // Inherits: id, name, adventureId, attributes, createdAt
  // Omits: modifiers (not needed for list display), updatedAt
}

/**
 * Result of a single 4d6 dice roll (dropping lowest die)
 * Used during character creation in dice-roll mode
 *
 * @example
 * ```typescript
 * const roll: DiceRoll = {
 *   dice: [3, 5, 6, 2],
 *   dropped: 3,
 *   sum: 14  // 3 + 5 + 6 = 14 (dropped the 2)
 * };
 * ```
 */
export interface DiceRoll {
  /**
   * Four d6 results (each value 1-6)
   * Tuple type ensures exactly 4 dice
   */
  dice: [number, number, number, number];

  /**
   * Index of the dropped die (0-3)
   * Used for visual highlighting in UI
   */
  dropped: number;

  /**
   * Final sum (3-18)
   * Calculated as: sum of three highest dice
   */
  sum: number;

  /**
   * Optional timestamp for animation or roll history
   * Milliseconds since epoch
   */
  timestamp?: number;
}

/**
 * Point-buy cost lookup table
 * Maps attribute values to their point cost
 * Based on D&D 5E standard point-buy system
 */
export const POINT_BUY_COSTS: Record<number, number> = {
  8: 0, // Starting value (free)
  9: 1,
  10: 1,
  11: 1,
  12: 1,
  13: 1,
  14: 2,
  15: 2,
  16: 3,
  17: 3,
  18: 4,
};

/**
 * Attribute name mapping for display in UI
 */
export const ATTRIBUTE_NAMES: Record<AttributeKey, string> = {
  str: "Strength",
  dex: "Dexterity",
  int: "Intelligence",
  con: "Constitution",
  cha: "Charisma",
};

/**
 * Default starting attributes for new characters
 * Used when creating a character form without pre-populated data
 */
export const DEFAULT_ATTRIBUTES: Attributes = {
  str: 10,
  dex: 10,
  int: 10,
  con: 10,
  cha: 10,
};

/**
 * Attribute value constraints
 */
export const ATTRIBUTE_CONSTRAINTS = {
  MIN: 3,
  MAX: 18,
} as const;

/**
 * Point-buy system constraints
 */
export const POINT_BUY_CONSTRAINTS = {
  POOL: 27,
  STARTING_ATTRIBUTE: 8,
} as const;
